// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
        int n = Integer.parseInt(args[0]);
		int above = 0;
		int below = 0;

		for(int i = 0; i < n; i++)
		{
			if(Math.random() < 0.5)
			{
				below++;
			}
			else
			{
				above++;
			}
		}

        if(above == 0 || below == 0)
		{
			System.out.println("> 0.5 = " + above);
			System.out.println("< 0.5 = " + below);
		}
		else
		{
			float ratio = (float) Math.min(above, below) / Math.max(above, below);
        	System.out.println("> 0.5 = " + above);
			System.out.println("< 0.5 = " + below);
			System.out.println("Ratio = " + ratio);
		}
	}
}
